name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - 'musubi.moe/main'
      - 'musubi.moe/develop'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+\+musubi-moe*'
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
      - src/**.rs
      - Cargo.*
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
      - src/**.rs
      - Cargo.*

permissions:
  contents: read
  packages: write

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-platforms: ['linux/amd64', 'linux/arm64']
    outputs:
      docker-digest-${{ matrix.docker-platforms }}: steps.build.outputs.digest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.docker-platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - run: echo "DOCKER_IMAGE=${DOCKER_IMAGE,,}" >>${GITHUB_ENV} # repository name must be lowercase
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.docker-platforms }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME/${{ matrix.docker-platforms }}
          cache-to: type=gha,scope=$GITHUB_REF_NAME/${{ matrix.docker-platforms }},mode=max
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.DOCKER_IMAGE }},push-by-digest=${{ github.event_name != 'pull_request' }},name-canonical=true,push=${{ github.event_name != 'pull_request' }}

  mix:
    if: github.event_name != 'pull_request'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - run: echo "DOCKER_IMAGE=${DOCKER_IMAGE,,}" >>${GITHUB_ENV} # repository name must be lowercase
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=musubi.moe/main
            type=edge,branch=musubi.moe/develop
            type=semver,pattern={{raw}}
            type=ref,event=pr
      - name: Create manifest list and push
        env:
          DIGESTS: ${{ join(needs.build.outputs.*, '\n') }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s ' "$DIGESTS")
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }}
